# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
development:
  adapter: postgresql
  encoding: unicode
  database: ua-parm
  username: <%= Rails.application.credentials.dig(:development, :postgres_username)%>
  password: <%= Rails.application.credentials.dig(:development, :postgres_password) %>
