development:
  adapter: postgresql
  encoding: unicode
  database: ua-parm
  username: <%= Rails.application.credentials.dig(:postgres_username)%>
  password: <%= Rails.application.credentials.dig(:postgres_password)%>
